import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MaterialTable from "material-table";
// import Edit from "@material-ui/icons/Edit";
// import { forwardRef } from "react";

export default function Home() {
  // const tableIcons = {
  //   Delete: forwardRef((props, ref) => <DeleteOutline {...props} ref={ref} />),
  //   Edit: forwardRef((props, ref) => <Edit {...props} ref={ref} />),
  // };

  const columnas = [
    {
      title: "Artista",
      field: "artista",
    },
    {
      title: "País de origen",
      field: "pais",
    },
    {
      title: "Genero(s)",
      field: "genero",
    },
    {
      title: "Ventas estimadas (en millones)",
      field: "ventas",
      type: "numeric",
    },
  ];

  const data = [
    {
      artista: "The Beatles",
      pais: "Reuno Unido",
      genero: "Rock, pop",
      ventas: 1000,
    },
    {
      artista: "Elvis Presley",
      pais: "USA",
      genero: "Rock",
      ventas: 345,
    },
    {
      artista: "Juanes",
      pais: "Medellín",
      genero: "Rock, pop",
      ventas: 4543,
    },
    {
      artista: "Aterciopelados",
      pais: "Colombia",
      genero: "Rock",
      ventas: 100,
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Data Table con Material</h1>

        <p>Versión Mobile </p>
        <MaterialTable
          columns={columnas}
          data={data}
          title="Artistas más vendedores en el mundo"
          actions={[
            {
              icon: "edit",
              tooltip: "editar artista",
              onclick: (event, rowData) =>
                alert("Has editado el artista: " + rowData.artista),
            },
            {
              icon: "delete",
              tooltip: "Eliminar artista",
              onclick: (event, rowData) =>
                window.confirm(
                  "Has editado el artista: " + rowData.artista + "?"
                ),
            },
          ]}
        >
          <h1>Mi Primera tabla en react</h1>
        </MaterialTable>
      </main>
      <div className={styles.dataDesk}>
        <p>Versión Escritorio </p>

        <MaterialTable
          columns={columnas}
          data={data}
          title="Artistas más vendedores en el mundo"
          actions={[
            {
              icon: "edit",
              tooltip: "editar artista",
              onclick: (event, rowData) =>
                alert("Has editado el artista: " + rowData.artista),
            },
            {
              icon: "delete",
              tooltip: "Eliminar artista",
              onclick: (event, rowData) =>
                window.confirm(
                  "Has editado el artista: " + rowData.artista + "?"
                ),
            },
          ]}
          options={{
            actionsColumnIndex: -1,
          }}
          localization={{
            header: {
              actions: "Acciones",
            },
          }}
        >
          <h1>Mi Primera tabla en react</h1>
        </MaterialTable>
      </div>
    </div>
  );
}
